'use strict'

const measures = [{
    field: `temperature`,
    label: `Temperature`,
    type: `temperature`,
    unit: `°C`,
    accuracy: 2,
}, {
    field: `humidity`,
    label: `Humidity`,
    type: `humidity`,
    unit: `%`,
    accuracy: 2,
}, {
    field: `pressure`,
    label: `Pressure`,
    type: `pressure`,
    unit: `hPa`,
    accuracy: 0,
    scale: 0.01,
}, {
    field: `battery`,
    label: `Battery`,
    icon: `battery-bluetooth-variant`,
    unit: `mV`,
    accuracy: 0,
}, {
    field: `battery_level`,
    label: `Battery Level`,
    type: `battery`,
    unit: `%`,
    accuracy: 0,
}, {
    field: `accelerationX`,
    label: `Acceleration X`,
    icon: `axis-x-arrow`,
    unit: `mG`,
    accuracy: 0,
    required: [`acceleration`],
}, {
    field: `accelerationY`,
    label: `Acceleration Y`,
    icon: `axis-y-arrow`,
    unit: `mG`,
    accuracy: 0,
    required: [`acceleration`],
}, {
    field: `accelerationZ`,
    label: `Acceleration Z`,
    icon: `axis-z-arrow`,
    unit: `mG`,
    accuracy: 0,
    required: [`acceleration`],
}, {
    field: `rssi`,
    label: `RSSI`,
    type: `signal_strength`,
    unit: `dBm`,
    accuracy: 0,
}, {
    field: `acceleration`,
    label: `Acceleration`,
    icon: `speedometer`,
    unit: `mG`,
    accuracy: 0,
    required: [`accelerationX`, `accelerationY`, `accelerationZ`],
}, {
    field: `equilibrium_vapor_pressure`,
    label: `Equilibrium Vapor Pressure`,
    type: `pressure`,
    unit: `hPa`,
    scale: 0.01,
    required: [`temperature`],
}, {
    field: `absolute_humidity`,
    label: `Absolute Humidity`,
    icon: `water`,
    unit: `g/m3`,
    required: [`temperature`, `humidity`],
}, {
    field: `air_density`,
    label: `Air Density`,
    icon: `air-filter`,
    unit: `kg/m3`,
    required: [`temperature`, `humidity`, `pressure`],
}, {
    field: `dew_point`,
    label: `Dew Point`,
    type: `temperature`,
    unit: `°C`,
    required: [`temperature`, `humidity`],
}, {
    field: `vapor_pressure_deficit`,
    label: `Vapor Pressure Deficit`,
    type: `pressure`,
    unit: `hPa`,
    required: [`temperature`, `humidity`],
}, {
    field: `txPower`,
    label: `Tx Power`,
    type: `signal_strength`,
    unit: `dBm`,
    accuracy: 1,
}, {
    field: `movementCounter`,
    label: `Movement Counter`,
    // icon: `battery-bluetooth-variant`,
    unit: `count`,
    accuracy: 0,
}, {
    field: `measurementSequenceNumber`,
    label: `Measurement Sequence Number`,
    // icon: `battery-bluetooth-variant`,
    unit: `count`,
    accuracy: 0,
}, {
    field: `samples`,
    label: `History Samples`,
    unit: `count`,
    accuracy: 0,
}, {
    field: `frequency`,
    label: `Frequency`,
    unit: `count/min`,
    accuracy: 1,
    toFixed: 1,
}, {
    field: `period`,
    label: `Period`,
    unit: `seconds`,
    accuracy: 0,
    toFixed: 0,
}]

module.exports = measures
